import { UserInterface } from "./user";
import { IBankDetail, IWalletDetail } from "./client";

export interface IAgents {
    _id: string;
    email: string;
    isVerified: boolean;
    agentId: string;
    referralCode?: string | null;
    fullName: string | null;
    firstName: string;
    lastName: string;
    dateOfBirth: string | null;
    gender: "male" | "female" | "other" | null;
    profileImage: string | null;
    phoneNumber: string | null;
    country: string | null;
    countryCode: string | null;
    state: string | null;
    city: string | null;
    address: string | null;
    postalCode: string | null;
    preferredCurrency: string;
    agentLevel: string;
    commissionPercentage: number;
    commissionTierPolicy?: {
        _id: string;
        name: string;
        slug: string;
        commissionRate: number;
        active: boolean;
        isDefault: boolean;
    } | string | null;
    isCommissionEligible: boolean;
    salaryActivated?: boolean;
    isSalaryEligibleThisMonth?: boolean;
    salesThisMonth?: number;
    joiningDate: string;
    sponsorAgent: IAgents | null;
    kycStatus: "pending" | "under_review" | "approved" | "rejected";
    kycVerification: {
        liveSelfie: string | null;
        selfDeclarationVideo: string | null;
        governmentIdType: "passport" | "national_id" | "driving_license" | "voter_id" | "aadhaar" | "pan" | "other" | null;
        governmentIdNumber: string | null;
        governmentIdFront: string | null;
        governmentIdBack: string | null;
        remarks: string | null;
        submittedAt: string | null;
        verifiedAt: string | null;
        verifiedBy: UserInterface | null;
    };
    bankDetails: IBankDetail[];
    wallets: IWalletDetail[];
    totalClients: number;
    activeClients: number;
    totalInvestmentVolume: number;
    managedInvestmentVolume?: number;
    lifetimeBusinessVolume: number;
    totalDeposits: number;
    totalWithdrawals: number;
    totalCommissionEarned: number;
    totalCommissionPaid: number;
    pendingCommission: number;
    availableCommissionBalance: number;
    lastCommissionPaidAt: string | null;
    isKycRequired: boolean;
    isProfileCompleted: boolean;
    currentPassword?: string | null;
    notes: string | null;
    createdBy: UserInterface | null;
    updatedBy: UserInterface | null;
    status: "pending" | "active" | "inactive" | "suspended" | "blocked" | "closed";
    createdAt: string;
    updatedAt: string;
}
