export type BondStatus = "draft" | "active" | "inactive" | "matured" | "archived";
export type BondRisk = "low" | "medium" | "high" | "very_high";
export type CouponFrequency = "monthly" | "quarterly" | "semiannual" | "annual" | "maturity";

export interface BondInterface {
    _id?: string;
    name: string;
    code: string;
    slug: string;
    shortDescription?: string;
    description?: string;
    currency: "USD";
    minInvestment: number;
    maxInvestment?: number | null;
    termMonths: number;
    couponRateAnnual: number;
    couponFrequency: CouponFrequency;
    usdtBenefitEnabled: boolean;
    usdtBenefitPercent: number;
    usdtLockType: "same_as_bond" | "custom";
    usdtLockMonths?: number | null;
    usdtUnlockMethod: "automatic" | "admin_approval";
    usdtDescription?: string;
    earlyRedemptionAllowed: boolean;
    minHoldingMonths: number;
    noticeDays: number;
    principalPenaltyPercent: number;
    usdtEarlyExitTreatment: "full_forfeit" | "partial_forfeit" | "retain" | "admin_review";
    usdtPartialForfeitPercent?: number | null;
    unpaidCouponTreatment: "forfeit" | "pay_accrued" | "admin_review";
    paidCouponTreatment: "no_clawback" | "full_clawback" | "partial_clawback";
    paidCouponClawbackPercent?: number | null;
    redemptionFeePercent: number;
    earlyRedemptionTerms?: string;
    riskLevel: BondRisk;
    termsAndConditions?: string;
    riskDisclosure?: string;
    usdtDisclosure?: string;
    offeringDocumentUrl?: string;
    termSheetUrl?: string;
    internalNotes?: string;
    status: BondStatus;
    featured: boolean;
    sortOrder: number;
    version?: number;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
}
