"use client";

import { useEffect, useState } from "react";
import { Loader2, Mail, RefreshCw } from "lucide-react";
import appClient from "@/lib/appClient";

type EmailLog = { _id: string; type: string; applicationReference: string; recipient: string; subject: string; status: "pending" | "sent" | "failed"; attempts: number; lastError?: string; sentAt?: string; createdAt: string };
const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("en-SG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function HiringEmailLogsPage() {
    const [logs, setLogs] = useState<EmailLog[]>([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [retrying, setRetrying] = useState("");
    const load = async () => { setLoading(true); setError(""); try { const response = await appClient.get("/api/hiring/email-logs", { params: { limit: 100, ...(status ? { status } : {}) } }); setLogs(response.data.data || []); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load email logs."); } finally { setLoading(false); } };
    useEffect(() => { void load(); }, [status]);
    const retry = async (id: string) => { setRetrying(id); setError(""); try { await appClient.post(`/api/hiring/email-logs/${id}/retry`); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not retry email."); } finally { setRetrying(""); } };
    return <div className="mx-auto w-full max-w-[1400px] space-y-5 pb-10"><header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-widest text-slate-400"><Mail className="h-3.5 w-3.5 text-navy" />Hiring</div><h1 className="mt-1 text-2xl font-extrabold text-navy">Candidate Emails</h1><p className="mt-1 text-xs text-slate-500">Delivery history for candidate-facing hiring notifications.</p></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs"><option value="">All delivery states</option><option value="sent">Sent</option><option value="failed">Failed</option><option value="pending">Pending</option></select></header>{error && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}{loading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600" /></div> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Application</th><th>Notification</th><th>Recipient</th><th>Status</th><th>Sent / created</th><th className="px-5 text-right">Action</th></tr></thead><tbody>{logs.map((item) => <tr key={item._id} className="border-t border-slate-100 text-xs"><td className="px-5 py-4 font-bold text-navy">{item.applicationReference}</td><td><p className="font-semibold text-slate-700">{item.subject}</p><p className="text-[9px] text-slate-400">{item.type.replaceAll("_", " ")} · {item.attempts} attempt(s)</p></td><td className="text-slate-500">{item.recipient}</td><td><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${item.status === "sent" ? "bg-emerald-50 text-emerald-700" : item.status === "failed" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{item.status}</span>{item.lastError && <p className="mt-1 max-w-56 truncate text-[9px] text-red-500">{item.lastError}</p>}</td><td className="text-slate-500">{dateTime(item.sentAt || item.createdAt)}</td><td className="px-5 text-right">{item.status === "failed" && <button onClick={() => retry(item._id)} disabled={retrying === item._id} className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-[10px] font-bold text-navy"><RefreshCw className={`h-3 w-3 ${retrying === item._id ? "animate-spin" : ""}`} /> Retry</button>}</td></tr>)}</tbody></table></div></section>}</div>;
}
